import React, { useState, useEffect, useCallback } from 'react'
import { supabase } from './supabaseClient'
const C={navy:'#1a1a2e',navyLt:'#2d2d4a',teal:'#2a9d8f',tealDk:'#21867a',tealLt:'#e6f5f2',coral:'#e07a5f',coralLt:'#fef0ec',gold:'#d4a84b',goldLt:'#fdf6e8',cream:'#F5F3EF',white:'#FFFFFF',s50:'#f8f9fa',s100:'#f1f3f5',s200:'#e9ecef',s400:'#adb5bd',s500:'#868e96',s600:'#495057',s700:'#343a40',blue:'#457b9d',blueLt:'#edf4f8'}
const fmt=n=>n==null?'$0.00':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(typeof n==='string'?parseFloat(n):n)
const fmtD=d=>d?new Date(d+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}):'—'
const mn=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
const Pill=({label,value,color})=><div style={{flex:'1 1 180px',padding:'14px 16px',borderRadius:10,background:C.white,borderLeft:'4px solid '+color,boxShadow:'0 1px 3px rgba(0,0,0,0.06)'}}><div style={{fontSize:10,fontWeight:600,color:C.s500,textTransform:'uppercase',letterSpacing:0.5}}>{label}</div><div style={{fontSize:20,fontWeight:700,color,marginTop:3}}>{value}</div></div>
const Badge=({text,color})=><span style={{display:'inline-block',padding:'2px 8px',borderRadius:99,fontSize:10,fontWeight:600,background:color==='green'?C.tealLt:color==='red'?C.coralLt:color==='gold'?C.goldLt:C.blueLt,color:color==='green'?C.tealDk:color==='red'?C.coral:color==='gold'?'#b8860b':C.blue}}>{text}</span>
const Card=({icon,title,sub,children})=><div style={{background:C.white,borderRadius:12,padding:'18px 20px',boxShadow:'0 1px 3px rgba(0,0,0,0.06)'}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:14}}><div><div style={{fontSize:14,fontWeight:600,color:C.navy}}>{icon&&<span style={{marginRight:6}}>{icon}</span>}{title}</div>{sub&&<div style={{fontSize:11,color:C.s500,marginTop:1}}>{sub}</div>}</div></div>{children}</div>
const Empty=({icon,msg})=><div style={{textAlign:'center',padding:'30px 16px',color:C.s400}}><div style={{fontSize:28,marginBottom:6}}>{icon}</div><div style={{fontSize:12}}>{msg}</div><div style={{fontSize:11,marginTop:6}}>Add data through Claude chat or Supabase</div></div>
const TH=({children,right})=><th style={{textAlign:right?'right':'left',padding:'6px 10px',fontSize:10,fontWeight:600,color:C.s500,textTransform:'uppercase',borderBottom:'2px solid '+C.s200}}>{children}</th>
const TD=({children,right,style:s={}})=><td style={{padding:'8px 10px',textAlign:right?'right':'left',color:C.s700,...s}}>{children}</td>
const Tbl=({cols,rows,eI,eM})=>{if(!rows||!rows.length)return <Empty icon={eI||'📋'} msg={eM||'No data yet'}/>;return <table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}><thead><tr>{cols.map((c,i)=><TH key={i} right={c.right}>{c.label}</TH>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} style={{borderBottom:'1px solid '+C.s100}}>{cols.map((c,j)=><TD key={j} right={c.right} style={c.style?c.style(r):{}}>{c.render?c.render(r):r[c.key]}</TD>)}</tr>)}</tbody></table>}

export default function App(){
const[tab,setTab]=useState('overview')
const[loading,setLoading]=useState(true)
const[data,setData]=useState({})
const load=useCallback(async()=>{setLoading(true);try{const y=new Date().getFullYear(),m=new Date().getMonth()+1
const[sR,bR,cR,tR,biR,buR,iR,eR,rR,pR,spR,piR]=await Promise.all([supabase.rpc('get_dashboard_summary'),supabase.from('cf_bank_accounts').select('*').order('entity').order('account_name'),supabase.from('cf_credit_accounts').select('*').order('entity').order('account_name'),supabase.from('cf_transactions').select('*').order('transaction_date',{ascending:false}).limit(50),supabase.from('cf_bills').select('*').eq('is_active',true).order('due_day'),supabase.from('cf_budget_categories').select('*').eq('year',y),supabase.from('cf_income_sources').select('*').order('entity'),supabase.from('cf_hgp_expenses').select('*').order('expense_date',{ascending:false}).limit(30),supabase.from('cf_hgp_revenue').select('*').order('revenue_date',{ascending:false}).limit(30),supabase.from('cf_hgp_monthly_pl').select('*').order('year').order('month'),supabase.from('cf_household_spending').select('*').eq('year',y).eq('month',m),supabase.from('cf_pending_invoices').select('*').order('due_date')])
setData({summary:sR.data||{},bankAccounts:bR.data||[],creditAccounts:cR.data||[],transactions:tR.data||[],bills:biR.data||[],budgetCategories:buR.data||[],incomeSources:iR.data||[],hgpExpenses:eR.data||[],hgpRevenue:rR.data||[],hgpPL:pR.data||[],householdSpending:spR.data||[],pendingInvoices:piR.data||[]})}catch(e){console.error(e)}setLoading(false)},[])
useEffect(()=>{load()},[load])
const s=data.summary||{},hN=(s.hgp_revenue_mtd||0)-(s.hgp_expenses_mtd||0)
const tabs=[{id:'overview',label:'Overview',icon:'🏠'},{id:'hgp',label:'HGP Business',icon:'🏢'},{id:'bills',label:'Bills & Accounts',icon:'📅'}]
if(loading)return <div style={{minHeight:'100vh',background:C.cream,display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{textAlign:'center',color:C.s500}}><div style={{fontSize:32,marginBottom:8}}>⏳</div><div style={{fontSize:14}}>Loading Cooper BCC...</div></div></div>
return(
<div style={{minHeight:'100vh',background:C.cream,fontFamily:"'DM Sans',sans-serif"}}>
<div style={{background:'linear-gradient(135deg,'+C.navy+','+C.navyLt+')',padding:'14px 20px',display:'flex',justifyContent:'space-between',alignItems:'center'}}>
<div><div style={{fontSize:17,fontWeight:700,color:C.white}}>Cooper Household</div><div style={{fontSize:10,color:'rgba(255,255,255,0.55)',marginTop:1}}>Business Command Center</div></div>
<div style={{display:'flex',gap:10,alignItems:'center'}}><div style={{fontSize:11,color:'rgba(255,255,255,0.6)'}}>{new Date().toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}</div>
<button onClick={load} style={{background:'rgba(255,255,255,0.12)',border:'none',borderRadius:6,color:C.white,padding:'5px 12px',fontSize:11,cursor:'pointer'}}>↻ Refresh</button></div></div>
<div style={{background:C.white,borderBottom:'1px solid '+C.s200,padding:'0 20px',display:'flex',gap:2}}>
{tabs.map(t=><button key={t.id} onClick={()=>setTab(t.id)} style={{padding:'10px 14px',border:'none',background:'none',cursor:'pointer',fontSize:12,fontWeight:tab===t.id?600:400,color:tab===t.id?C.teal:C.s500,borderBottom:'2px solid '+(tab===t.id?C.teal:'transparent')}}>{t.icon} {t.label}</button>)}</div>
<div style={{padding:16,maxWidth:960,margin:'0 auto'}}>
{tab==='overview'&&<div style={{display:'flex',flexDirection:'column',gap:16}}>
<div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Pill label="HGP Revenue MTD" value={fmt(s.hgp_revenue_mtd)} color={C.teal}/><Pill label="HGP Net MTD" value={fmt(hN)} color={hN>=0?C.teal:C.coral}/><Pill label="HGP Revenue YTD" value={fmt(s.hgp_revenue_ytd)} color={C.blue}/><Pill label="Active Contracts" value={s.active_hgp_contracts||0} color={C.blue}/></div>
<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
<Card icon="📊" title="Quick Stats" sub={new Date().toLocaleDateString('en-US',{month:'long',year:'numeric'})}>
<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}>{[{l:'Revenue MTD',v:fmt(s.hgp_revenue_mtd),c:C.teal},{l:'Expenses MTD',v:fmt(s.hgp_expenses_mtd),c:C.coral},{l:'Pending Invoices',v:fmt(s.pending_invoices),c:C.gold},{l:'Active Clients',v:s.total_hgp_clients||0,c:C.blue},{l:'Monthly Bills',v:fmt(s.bills_total_monthly),c:C.s600},{l:'Bills Count',v:s.bills_due_this_month||0,c:C.s600}].map((x,i)=><div key={i} style={{padding:'8px 10px',background:C.s50,borderRadius:6}}><div style={{fontSize:10,color:C.s500,fontWeight:500}}>{x.l}</div><div style={{fontSize:15,fontWeight:700,color:x.c,marginTop:2}}>{x.v}</div></div>)}</div></Card>
<Card icon="📈" title="HGP Monthly P&L" sub="Revenue vs Expenses"><Tbl cols={[{label:'Month',render:r=>mn[(r.month||1)-1]+' '+r.year},{label:'Revenue',right:true,render:r=><span style={{color:C.teal,fontWeight:600}}>{fmt(r.revenue)}</span>},{label:'Expenses',right:true,render:r=><span style={{color:C.coral}}>{fmt(r.expenses)}</span>},{label:'Net',right:true,render:r=><span style={{fontWeight:700,color:parseFloat(r.net_income)>=0?C.teal:C.coral}}>{fmt(r.net_income)}</span>}]} rows={data.hgpPL} eI="📈" eM="P&L loading..."/></Card></div>
<Card icon="🔄" title="Recent Transactions" sub="All entities"><Tbl cols={[{label:'Date',render:r=>fmtD(r.transaction_date)},{label:'Description',key:'description'},{label:'Category',render:r=><Badge text={r.category} color="blue"/>},{label:'Amount',right:true,render:r=><span style={{fontWeight:600,color:r.amount>0?C.teal:C.coral}}>{fmt(r.amount)}</span>}]} rows={(data.transactions||[]).slice(0,10)} eI="🔄" eM="No transactions yet"/></Card></div>}
{tab==='hgp'&&<div style={{display:'flex',flexDirection:'column',gap:16}}>
<div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Pill label="Revenue MTD" value={fmt(s.hgp_revenue_mtd)} color={C.teal}/><Pill label="Expenses MTD" value={fmt(s.hgp_expenses_mtd)} color={C.coral}/><Pill label="Net Income MTD" value={fmt(hN)} color={hN>=0?C.teal:C.coral}/><Pill label="Active Contracts" value={s.active_hgp_contracts||0} color={C.blue}/></div>
<Card icon="📊" title="Profit & Loss" sub="Home Guardian Pro — 2026"><Tbl cols={[{label:'Month',render:r=>mn[(r.month||1)-1]+' '+r.year},{label:'Revenue',right:true,render:r=><span style={{color:C.teal,fontWeight:600}}>{fmt(r.revenue)}</span>},{label:'Expenses',right:true,render:r=><span style={{color:C.coral}}>{fmt(r.expenses)}</span>},{label:'Net',right:true,render:r=><span style={{fontWeight:700,color:parseFloat(r.net_income)>=0?C.teal:C.coral}}>{fmt(r.net_income)}</span>}]} rows={data.hgpPL} eI="📊" eM="P&L loading..."/></Card>
<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
<Card icon="💰" title="Revenue Detail" sub="Paid invoices & condo checks">{(data.hgpRevenue||[]).length>0?<div style={{maxHeight:280,overflowY:'auto'}}>{(data.hgpRevenue||[]).map((r,i)=><div key={i} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'8px 0',borderBottom:'1px solid '+C.s100}}><div><div style={{fontSize:12,fontWeight:500,color:C.s700}}>{r.client_name}</div><div style={{fontSize:10,color:C.s500}}>{fmtD(r.revenue_date)} · <Badge text={r.revenue_type} color="green"/></div></div><div style={{fontSize:13,fontWeight:600,color:C.teal}}>{fmt(r.amount)}</div></div>)}</div>:<Empty icon="💰" msg="No revenue yet"/>}</Card>
<Card icon="🧾" title="Business Expenses" sub="Home Guardian Pro">{(data.hgpExpenses||[]).length>0?<div style={{maxHeight:280,overflowY:'auto'}}>{(data.hgpExpenses||[]).map((r,i)=><div key={i} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'8px 0',borderBottom:'1px solid '+C.s100}}><div><div style={{fontSize:12,fontWeight:500,color:C.s700}}>{r.description}</div><div style={{fontSize:10,color:C.s500}}>{fmtD(r.expense_date)} · <Badge text={r.category} color="red"/></div></div><div style={{fontSize:13,fontWeight:600,color:C.coral}}>{fmt(r.amount)}</div></div>)}</div>:<Empty icon="🧾" msg="No expenses yet"/>}</Card></div></div>}
{tab==='bills'&&<div style={{display:'flex',flexDirection:'column',gap:16}}>
<div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Pill label="Monthly Bills" value={fmt(s.bills_total_monthly)} color={C.s600}/><Pill label="Active Bills" value={s.bills_due_this_month||0} color={C.blue}/><Pill label="Bank Total" value={fmt(s.bank_total)} color={C.teal}/><Pill label="Credit Debt" value={fmt(s.credit_total)} color={C.coral}/></div>
<Card icon="📅" title="Recurring Bills" sub="Active monthly obligations"><Tbl cols={[{label:'Bill',key:'bill_name'},{label:'Category',render:r=><Badge text={r.category} color="blue"/>},{label:'Amount',right:true,render:r=>parseFloat(r.amount)>0?fmt(r.amount):<span style={{color:C.s400,fontStyle:'italic'}}>needs amount</span>},{label:'Entity',render:r=><Badge text={r.entity} color={r.entity==='hgp'?'green':'gold'}/>},{label:'Autopay',render:r=>r.autopay?<Badge text="Auto" color="green"/>:<Badge text="Manual" color="gold"/>}]} rows={data.bills} eI="📅" eM="No bills yet"/></Card>
<Card icon="💵" title="Income Sources"><Tbl cols={[{label:'Source',key:'source_name'},{label:'Type',render:r=><Badge text={r.source_type} color="green"/>},{label:'Entity',render:r=><Badge text={r.entity} color={r.entity==='hgp'?'green':'gold'}/>},{label:'Frequency',key:'frequency'},{label:'Expected',right:true,render:r=>parseFloat(r.expected_amount)>0?fmt(r.expected_amount):<span style={{color:C.s400,fontStyle:'italic'}}>update</span>}]} rows={data.incomeSources} eI="💵" eM="No income sources yet"/></Card></div>}</div>
<div style={{textAlign:'center',padding:'14px 20px',fontSize:10,color:C.s400,borderTop:'1px solid '+C.s200,marginTop:30}}>Cooper Household BCC · Live from Supabase · Managed via Claude</div></div>)}
